name: Update Anime Rankings

on:
  schedule:
    # Run every Saturday at 8pm UTC (20:00)
    - cron: '0 20 * * 6'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-rankings:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests-html
        pyppeteer-install  # Correct command to install Chromium
        
    - name: Fetch anime data
      run: |
        echo "Fetching anime data..."
        python scripts/fetch_anime_data.py || echo "API fetch failed, continuing with existing data..."
        
    - name: Fetch MAL scores
      run: |
        echo "Fetching MAL scores..."
        python scripts/fetch_mal_scores.py || echo "MAL fetch failed, continuing with existing data..."
        
    - name: Fetch AniTrendz rankings
      run: |
        echo "Fetching AniTrendz rankings..."
        python scripts/fetch_anitrendz.py || echo "AniTrendz fetch failed, continuing with existing data..."
        
    - name: Generate rankings page
      run: |
        echo "Generating rankings HTML..."
        python scripts/generate_rankings.py
        
    - name: Generate main page
      run: |
        echo "Generating main HTML page..."
        python scripts/generate_html.py
        
    - name: Pull latest changes
      run: git pull --rebase origin main
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🔄 Automated rankings update - $(date -u +'%Y-%m-%d %H:%M UTC')

          🤖 Generated with GitHub Actions
          
          - Updated anime data and rankings
          - Refreshed AniTrendz weekly scores
          - Regenerated HTML pages"
          git push
        fi
        
    - name: Create deployment comment
      if: success()
      run: |
        echo "✅ Rankings successfully updated on $(date -u +'%Y-%m-%d at %H:%M UTC')"
        echo "📊 Check the updated rankings at your deployed site"